version: 2.0

jobs:
  test:
    docker:
      - image: circleci/node:8.9.3
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package-lock.json" }}
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run test -- --coverage
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  lint_and_test:
    jobs:
      - test