version: 2.0

jobs:
  test:
    docker:
      - image: circleci/node:8.9.3
    steps:
      - checkout
      - restore_cache:
          keys:
          - dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          # only run npm ci if node_modules doesn't exist, as it clears
          # out node_modules and installs everything from scratch,
          # removing the benefit from using circle's caching
          command: |
            if [ ! -d node_modules ]; then
              npm ci
            fi
      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package-lock.json" }}
      - run: npm run lint
      - run: npm run typecheck
      - run: npm run test -- --coverage
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  lint_and_test:
    jobs:
      - test
