global:
  type: 'alerts'
  category: 'alerts'
imports:
  - ./color.yml
props:
  INFO:
    value: "#c3f9ff"
  CONFIRMATION:
    value: "#e4f7f1"
  ERROR:
    value: "#ffebee"
  WARNING:
    value: "#fff5ce"