global:
  type: 'color'
  category: 'button'
imports:
  - ./color.yml
props:
  BUTTON_PRIMARY_DEFAULT_BACKGROUND_COLOR:
    value: "{!GREEN500}"
  BUTTON_PRIMARY_HOVER_BACKGROUND_COLOR:
    value: "{!GREEN400}" 
  BUTTON_PRIMARY_FOCUS_BACKGROUND_COLOR:
    value: "{!GREEN600}"
  BUTTON_PRIMARY_FOCUS_SHADOW:
    value: "{!GREEN300}"
  BUTTON_SECONDARY_DEFAULT_BACKGROUND_COLOR: 
    value: "{!NAVY700}"
  BUTTON_SECONDARY_HOVER_BACKGROUND_COLOR:
    value: "{!NAVY600}"
  BUTTON_SECONDARY_ACTIVE_BACKGROUND_COLOR:
    value: "{!NAVY700}"
  BUTTON_SECONDARY_FOCUS_SHADOW:
    value: "{!GREY400}"