global:
  type: color
  category: colors
props: &COLORS
  WHITE:
    value: '#fff'
  BLACK:
    value: '#000'
  PINK300:
    value: '#FBDFE2'
  PINK400:
    value: '#FCB3C8'
  PINK500:
    value: '#F7707F'
  PINK600:
    value: '#E55565'
  PINK700:
    value: '#C83243'
  ORANGE300:
    value: '#FFEDB4'
  ORANGE400:
    value: '#FFCE5E'
  ORANGE500:
    value: '#FDB81C'
  ORANGE600:
    value: '#F6AF0D'
  ORANGE700:
    value: '#D89118'
  PURPLE300:
    value: '#e8e2f2'
  PURPLE400:
    value: '#D0B8FF'
  PURPLE500:
    value: '#9F81DA'
  PURPLE600:
    value: '#604E83'
  PURPLE700:
    value: '#443364'
  GREEN300:
    value: '#D8F0E8'
  GREEN400:
    value: '#4FD2A4'
  GREEN500:
    value: '#3eb38a'
  GREEN600:
    value: '#38A07C'
  GREEN700:
    value: '#298665'
  BLUE300:
    value: '#C1F4FF'
  BLUE400:
    value: '#65D2EA'
  BLUE500:
    value: '#54C3DB'
  BLUE600:
    value: '#4DB8CF'
  BLUE700:
    value: '#2BA7C2'
  NAVY300:
    value: '#F9FAFC'
  NAVY400:
    value: '#C6C7D8'
  NAVY500:
    value: '#93A6C1'
  NAVY600:
    value: '#515277'
  NAVY700:
    value: '#302C50'
  GREY200:
    value: '#F9FAFC'
  GREY300:
    value: '#EEF4FA'
  GREY400:
    value: '#D0D8DF'
  GREY500:
    value: '#B0BAC3'
  GREY600:
    value: '#89929B'
  GREY700:
    value: '#707D8A'
  RED:
    value: '{!PINK500}'
  PINK:
    value: '{!PINK500}'
  BLUE:
    value: '{!BLUE500}'
  PURPLE:
    value: '{!PURPLE500}'
  ORANGE:
    value: '{!ORANGE500}'
  GREEN:
    value: '{!GREEN500}'
  NAVY:
    value: '{!NAVY500}'
  GREY:
    value: '{!GREY600}'
  CHARCOAL:
    value: '{!NAVY700}'
  SLATE:
    value: '{!NAVY600}'
  SILVER:
    value: '{!GREY500}'
  PLATINUM:
    value: '{!GREY300}'
  SNOW:
    value: '{!GREY200}'
  NONE:
    value: ''
    type: string
  INHERIT:
    value: 'inherit'
    type: unit
  CURRENT_COLOR:
    value: 'currentColor'
    type: unit
aliases: *COLORS
